name: CI

on:
  push:
    branches:
      - main
      - 'claude/**'
  pull_request:
    branches:
      - main

jobs:
  plugin-tests:
    name: Plugin Tests (Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - elixir: '1.17.3'
            otp: '26.2'
          - elixir: '1.18.1'
            otp: '26.2'
          - elixir: '1.19.1'
            otp: '27.2'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Erlang/OTP and Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Install dependencies for test projects
        run: |
          echo "Installing dependencies for test projects..."
          for test_dir in test/plugins/*/; do
            for project_dir in "$test_dir"*/; do
              if [ -f "$project_dir/mix.exs" ]; then
                echo "Installing deps for $project_dir"
                cd "$project_dir"
                mix deps.get
                cd - > /dev/null
              fi
            done
          done

      - name: Run plugin test suite
        run: |
          chmod +x test/run-all-tests.sh
          ./test/run-all-tests.sh
